apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chat-app.fullname" . }}-env
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
data:
  ACME_EMAIL: {{ .Values.config.env.ACME_EMAIL | quote }}
  BASE_API_SLUG: {{ .Values.config.env.BASE_API_SLUG | quote }}
  CLIENT_URL: {{ .Values.config.env.CLIENT_URL | quote }}
  CORS_ORIGINS: {{ .Values.config.env.CORS_ORIGINS | quote }}
  DB_HOST: {{ include "chat-app.componentName" (dict "root" . "component" "db") | quote }}
  DB_NAME: {{ .Values.config.env.DB_NAME | quote }}
  DB_PORT: {{ .Values.config.env.DB_PORT | quote }}
  DB_USER: {{ .Values.config.env.DB_USER | quote }}
  DOMAIN: {{ .Values.config.env.DOMAIN | quote }}
  LOG_LEVEL: {{ .Values.config.env.LOG_LEVEL | quote }}
  NODE_ENV: {{ .Values.config.env.NODE_ENV | quote }}
  REDIS_HOST: {{ include "chat-app.componentName" (dict "root" . "component" "redis") | quote }}
  REDIS_PORT: {{ .Values.config.env.REDIS_PORT | quote }}
  REDIS_URL: {{ printf "redis://%s:%s" (include "chat-app.componentName" (dict "root" . "component" "redis")) .Values.config.env.REDIS_PORT | quote }}
  SERVER_HOST: {{ printf "%s.%s.svc.cluster.local" (include "chat-app.componentName" (dict "root" . "component" "server")) .Release.Namespace | quote }}
  SERVER_PORT: {{ .Values.config.env.SERVER_PORT | quote }}
  TRAEFIK_LOG_LEVEL: {{ .Values.config.env.TRAEFIK_LOG_LEVEL | quote }}
  VITE_API_URL: {{ .Values.config.env.VITE_API_URL | quote }}
  VITE_APP_NAME: {{ .Values.config.env.VITE_APP_NAME | quote }}
  VITE_APP_VERSION: {{ .Values.config.env.VITE_APP_VERSION | quote }}
  VITE_DEV_MODE: {{ .Values.config.env.VITE_DEV_MODE | quote }}
