apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.app.POSTGRES_PASSWORD | quote }}
  DB_PASSWORD: {{ .Values.secrets.app.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.app.JWT_SECRET | quote }}
  DB_URL: {{ .Values.secrets.app.DB_URL | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZURE_API_KEY: {{ .Values.secrets.azure.AZURE_API_KEY | quote }}
  AZURE_OPENAI_API_ENDPOINT: {{ .Values.secrets.azure.AZURE_OPENAI_API_ENDPOINT | quote }}
  AZURE_DEPLOYMENT_NAME: {{ .Values.secrets.azure.AZURE_DEPLOYMENT_NAME | quote }}
  AZURE_RESOURCE_NAME: {{ .Values.secrets.azure.AZURE_RESOURCE_NAME | quote }}
  SERPER_API_KEY: {{ .Values.secrets.azure.SERPER_API_KEY | quote }}
