{{- $appSecretName := .Values.secrets.app.existingSecret | default (printf "%s-app-secrets" (include "chat-app.fullname" .)) -}}
{{- if and .Values.secrets.create (not .Values.secrets.app.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appSecretName }}
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.app.data.POSTGRES_PASSWORD | quote }}
  DB_PASSWORD: {{ .Values.secrets.app.data.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.app.data.JWT_SECRET | quote }}
  DB_URL: {{ default (printf "postgres://%s:%s@%s:%s/%s" .Values.config.env.DB_USER .Values.secrets.app.data.DB_PASSWORD (include "chat-app.componentName" (dict "root" . "component" "db")) .Values.config.env.DB_PORT .Values.config.env.DB_NAME) .Values.secrets.app.data.DB_URL | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.app.data.OPENAI_API_KEY | quote }}
  SERPER_API_KEY: {{ .Values.secrets.app.data.SERPER_API_KEY | quote }}
  LANGFUSE_PUBLIC_KEY: {{ .Values.secrets.app.data.LANGFUSE_PUBLIC_KEY | quote }}
  LANGFUSE_SECRET_KEY: {{ .Values.secrets.app.data.LANGFUSE_SECRET_KEY | quote }}
  LANGFUSE_BASEURL: {{ .Values.secrets.app.data.LANGFUSE_BASEURL | quote }}
{{- end }}
