apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  labels:
    app.kubernetes.io/name: chat-app
    app.kubernetes.io/component: migration
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chat-app
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: chat-app-migrate:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: app-secrets
            - secretRef:
                name: azure-secrets
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  backoffLimit: 3