apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: server-sticky
  namespace: default
  labels:
    app.kubernetes.io/name: chat-app
    app.kubernetes.io/component: server
spec:
  weighted:
    services:
      - name: server
        port: 3000
        weight: 1
    sticky:
      cookie:
        name: server_sticky
        secure: true
        httpOnly: true
        sameSite: lax
